name: Docker Image CI - push
on: push
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
       docker build -t isaackwon/o2docker:base-latest --file base.Dockerfile .
       docker build -t isaackwon/o2docker:o2-latest -c10 --file O2.Dockerfile .
       
